services:
  iSponsorBlockTV:
    image: ghcr.io/dmunozv04/isponsorblocktv
    container_name: iSponsorBlockTV
    restart: unless-stopped
    network_mode: host
    volumes:
      # enter the same pathway as you used for your configurator in step 1
      - isponsorblocktv-data:/app/data
volumes:
  isponsorblocktv-data:
    driver: local
